# Site settings
title: Jeremy French
name: Jeremy French
email: jeremy@jeremyfrench.co.uk
description: > # this means to ignore newlines until "baseurl:"
  My Site, still on Jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.jeremyfrench.co.uk" # the base hostname & protocol for your site
twitter_username: jfrenchTweet
github_username:  jeremyfrench

# Build settings
markdown: kramdown
defaults:
   home:
     heading: "Jeremy French"
     subheading: "Sporadically blogging since 2010"

# url is currently only used only for the RSS feed in feed.xml
url: http://www.jeremyfrench.co.uk


# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-16084196-1'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: false
theme: jekyll-theme-yat
permalink: /:year/:month/:title
paginate: 3

highlighter: pygments
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
