# Site settings
title: Jeremy French
name: Jeremy French
email: jeremy@jeremyfrench.co.uk
description: > # this means to ignore newlines until "baseurl:"
  My Site, still on Jekyll, now powered by github pages
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.jeremyfrench.co.uk" # the base hostname & protocol for your site
github_username:  jeremyfrench
author: 
  picture: /assets/images/me.png
  name: Jeremy French
  url: https://www.jeremyfrench.co.uk


# Build settings
markdown: kramdown
defaults:
  - 
   scope:
     path: "" 
   values:   
     heading: "Jeremy French"
     subheading: "Online since the 90s"
  -
    scope:
      type: "posts"
    values:
      image:
        path: /assets/images/me.png
        height: 442
        width: 442
        alt: J French in green


# url is currently only used only for the RSS feed in feed.xml
url: http://www.jeremyfrench.co.uk


# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: false
permalink: /:year/:month/:title:output_ext
paginate: 3
paginate_path: "/blog/page:num/"

remote_theme: pages-themes/hacker@v0.2.0


highlighter: pygments
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

jekyll_tidy:
  exclude:
    - '**/*.scss'
    - '**/*.js'
    - '**/*.xml'
    - '**/*.atom'
